In [1]:
# Core libraries
import pandas as pd
import numpy as np

# NLP & ML
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Text cleaning
import re

In [2]:
def clean_text(text):
    text = text.lower()  # lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # remove special characters
    text = re.sub(r'\s+', ' ', text).strip()  # remove extra spaces
    return text

In [3]:
job_description = """
Looking for a Data Analyst skilled in Python, SQL, Power BI, and Machine Learning.
"""

resumes = [
    "Experienced in Python, SQL, and data visualization.",
    "Worked with Java and web development.",
    "Strong background in Python, Machine Learning, and data analysis."
]

In [4]:
job_description_clean = clean_text(job_description)
resumes_clean = [clean_text(resume) for resume in resumes]

In [5]:
# Combine JD + resumes
all_texts = [job_description_clean] + resumes_clean

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(all_texts)

In [7]:
jd_vector = vectors[0]

scores = []

for i in range(1, vectors.shape[0]):
    score = cosine_similarity(jd_vector, vectors[i])[0][0]
    scores.append(score)

In [9]:
results = pd.DataFrame({
    "Resume": resumes,
    "Score": scores
})

results["Score"] = results["Score"] * 100  # convert to %
results = results.sort_values(by="Score", ascending=False)
results["Score"] = results["Score"].round(2)
results.reset_index(drop=True, inplace=True)

results

results

                                              Resume  Score
0  Strong background in Python, Machine Learning,...  37.36
1  Experienced in Python, SQL, and data visualiza...  34.09
2              Worked with Java and web development.   3.88

In [10]:
pip install PyMuPDF

Collecting PyMuPDF
  Downloading pymupdf-1.27.2.2-cp310-abi3-win_amd64.whl.metadata (3.4 kB)
Downloading pymupdf-1.27.2.2-cp310-abi3-win_amd64.whl (19.2 MB)
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
    --------------------------------------- 0.3/19.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/19.2 MB 89.3 kB/s eta 0:03:30
   - -------------------------------------- 0.5/19.2 MB 89.3 kB/s eta 0:03:30
   - -------------------------------------- 0.5/19.2 MB 89.3 kB/s eta 0:03:30
   - -------------------------------------- 0.5/19.2 MB 89.3 kB/s eta 0:03:30
   - -------------------------------------- 0.5/19.2 MB 89.3 kB/s eta 0:03:30
   - -------------------------------------- 0.5/19.2 MB 89.3 kB/s eta 0:03:30
   - -------------------------------------- 0.5/19.2 MB 89.3 kB/s eta 0:03:30
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   - -------------------------------------- 0.8/19.2 MB 118.2 kB/s eta 0:02:37
   -- ------------------------------------- 1.0/19.2 MB 122.8 kB/s eta 0:02:29
   -- ------------------------------------- 1.0/19.2 MB 122.8 kB/s eta 0:02:29
   -- ------------------------------------- 1.0/19.2 MB 122.8 kB/s eta 0:02:29
   -- ------------------------------------- 1.0/19.2 MB 122.8 kB/s eta 0:02:29
   -- ------------------------------------- 1.0/19.2 MB 122.8 kB/s eta 0:02:29
   -- ------------------------------------- 1.0/19.2 MB 122.8 kB/s eta 0:02:29
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   -- ------------------------------------- 1.3/19.2 MB 135.9 kB/s eta 0:02:12
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.6/19.2 MB 135.9 kB/s eta 0:02:10
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   --- ------------------------------------ 1.8/19.2 MB 128.2 kB/s eta 0:02:16
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.1/19.2 MB 125.9 kB/s eta 0:02:17
   ---- ----------------------------------- 2.4/19.2 MB 122.4 kB/s eta 0:02:18
   ---- ----------------------------------- 2.4/19.2 MB 122.4 kB/s eta 0:02:18
   ---- ----------------------------------- 2.4/19.2 MB 122.4 kB/s eta 0:02:18
   ---- ----------------------------------- 2.4/19.2 MB 122.4 kB/s eta 0:02:18
   ---- ----------------------------------- 2.4/19.2 MB 122.4 kB/s eta 0:02:18
   ---- ----------------------------------- 2.4/19.2 MB 122.4 kB/s eta 0:02:18
   ---- ----------------------------------- 2.4/19.2 MB 122.4 kB/s eta 0:02:18
   ---- ----------------------------------- 2.4/19.2 MB 122.4 kB/s eta 0:02:18
   ----- ---------------------------------- 2.6/19.2 MB 124.3 kB/s eta 0:02:14
   ----- ---------------------------------- 2.6/19.2 MB 124.3 kB/s eta 0:02:14
   ----- ---------------------------------- 2.6/19.2 MB 124.3 kB/s eta 0:02:14
   ----- ---------------------------------- 2.6/19.2 MB 124.3 kB/s eta 0:02:14
   ----- ---------------------------------- 2.6/19.2 MB 124.3 kB/s eta 0:02:14
   ----- ---------------------------------- 2.6/19.2 MB 124.3 kB/s eta 0:02:14
   ----- ---------------------------------- 2.9/19.2 MB 129.7 kB/s eta 0:02:07
   ----- ---------------------------------- 2.9/19.2 MB 129.7 kB/s eta 0:02:07
   ----- ---------------------------------- 2.9/19.2 MB 129.7 kB/s eta 0:02:07
   ----- ---------------------------------- 2.9/19.2 MB 129.7 kB/s eta 0:02:07
   ----- ---------------------------------- 2.9/19.2 MB 129.7 kB/s eta 0:02:07
   ----- ---------------------------------- 2.9/19.2 MB 129.7 kB/s eta 0:02:07
   ----- ---------------------------------- 2.9/19.2 MB 129.7 kB/s eta 0:02:07
   ----- ---------------------------------- 2.9/19.2 MB 129.7 kB/s eta 0:02:07
   ------ --------------------------------- 3.1/19.2 MB 131.6 kB/s eta 0:02:03
   ------ --------------------------------- 3.1/19.2 MB 131.6 kB/s eta 0:02:03
   ------ --------------------------------- 3.1/19.2 MB 131.6 kB/s eta 0:02:03
   ------ --------------------------------- 3.1/19.2 MB 131.6 kB/s eta 0:02:03
   ------ --------------------------------- 3.1/19.2 MB 131.6 kB/s eta 0:02:03
   ------ --------------------------------- 3.1/19.2 MB 131.6 kB/s eta 0:02:03
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.4/19.2 MB 136.3 kB/s eta 0:01:57
   ------- -------------------------------- 3.7/19.2 MB 135.7 kB/s eta 0:01:55
   ------- -------------------------------- 3.7/19.2 MB 135.7 kB/s eta 0:01:55
   ------- -------------------------------- 3.7/19.2 MB 135.7 kB/s eta 0:01:55
   ------- -------------------------------- 3.7/19.2 MB 135.7 kB/s eta 0:01:55
   ------- -------------------------------- 3.7/19.2 MB 135.7 kB/s eta 0:01:55
   ------- -------------------------------- 3.7/19.2 MB 135.7 kB/s eta 0:01:55
   -------- ------------------------------- 3.9/19.2 MB 139.5 kB/s eta 0:01:50
   -------- ------------------------------- 3.9/19.2 MB 139.5 kB/s eta 0:01:50
   -------- ------------------------------- 3.9/19.2 MB 139.5 kB/s eta 0:01:50
   -------- ------------------------------- 3.9/19.2 MB 139.5 kB/s eta 0:01:50
   -------- ------------------------------- 3.9/19.2 MB 139.5 kB/s eta 0:01:50
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   -------- ------------------------------- 4.2/19.2 MB 143.7 kB/s eta 0:01:45
   --------- ------------------------------ 4.5/19.2 MB 142.7 kB/s eta 0:01:44
   --------- ------------------------------ 4.5/19.2 MB 142.7 kB/s eta 0:01:44
   --------- ------------------------------ 4.5/19.2 MB 142.7 kB/s eta 0:01:44
   --------- ------------------------------ 4.5/19.2 MB 142.7 kB/s eta 0:01:44
   --------- ------------------------------ 4.5/19.2 MB 142.7 kB/s eta 0:01:44
   --------- ------------------------------ 4.5/19.2 MB 142.7 kB/s eta 0:01:44
   --------- ------------------------------ 4.7/19.2 MB 151.3 kB/s eta 0:01:36
   --------- ------------------------------ 4.7/19.2 MB 151.3 kB/s eta 0:01:36
   --------- ------------------------------ 4.7/19.2 MB 151.3 kB/s eta 0:01:36
   --------- ------------------------------ 4.7/19.2 MB 151.3 kB/s eta 0:01:36
   --------- ------------------------------ 4.7/19.2 MB 151.3 kB/s eta 0:01:36
   --------- ------------------------------ 4.7/19.2 MB 151.3 kB/s eta 0:01:36
   --------- ------------------------------ 4.7/19.2 MB 151.3 kB/s eta 0:01:36
   --------- ------------------------------ 4.7/19.2 MB 151.3 kB/s eta 0:01:36
   ---------- ----------------------------- 5.0/19.2 MB 151.8 kB/s eta 0:01:34
   ---------- ----------------------------- 5.0/19.2 MB 151.8 kB/s eta 0:01:34
   ---------- ----------------------------- 5.0/19.2 MB 151.8 kB/s eta 0:01:34
   ---------- ----------------------------- 5.0/19.2 MB 151.8 kB/s eta 0:01:34
   ---------- ----------------------------- 5.0/19.2 MB 151.8 kB/s eta 0:01:34
   ---------- ----------------------------- 5.0/19.2 MB 151.8 kB/s eta 0:01:34
   ---------- ----------------------------- 5.0/19.2 MB 151.8 kB/s eta 0:01:34
   ---------- ----------------------------- 5.0/19.2 MB 151.8 kB/s eta 0:01:34
   ---------- ----------------------------- 5.2/19.2 MB 151.0 kB/s eta 0:01:33
   ---------- ----------------------------- 5.2/19.2 MB 151.0 kB/s eta 0:01:33
   ---------- ----------------------------- 5.2/19.2 MB 151.0 kB/s eta 0:01:33
   ---------- ----------------------------- 5.2/19.2 MB 151.0 kB/s eta 0:01:33
   ---------- ----------------------------- 5.2/19.2 MB 151.0 kB/s eta 0:01:33
   ---------- ----------------------------- 5.2/19.2 MB 151.0 kB/s eta 0:01:33
   ---------- ----------------------------- 5.2/19.2 MB 151.0 kB/s eta 0:01:33
   ---------- ----------------------------- 5.2/19.2 MB 151.0 kB/s eta 0:01:33
   ----------- ---------------------------- 5.5/19.2 MB 152.5 kB/s eta 0:01:31
   ----------- ---------------------------- 5.5/19.2 MB 152.5 kB/s eta 0:01:31
   ----------- ---------------------------- 5.5/19.2 MB 152.5 kB/s eta 0:01:31
   ----------- ---------------------------- 5.5/19.2 MB 152.5 kB/s eta 0:01:31
   ----------- ---------------------------- 5.5/19.2 MB 152.5 kB/s eta 0:01:31
   ----------- ---------------------------- 5.5/19.2 MB 152.5 kB/s eta 0:01:31
   ----------- ---------------------------- 5.5/19.2 MB 152.5 kB/s eta 0:01:31
   ----------- ---------------------------- 5.8/19.2 MB 151.6 kB/s eta 0:01:29
   ----------- ---------------------------- 5.8/19.2 MB 151.6 kB/s eta 0:01:29
   ----------- ---------------------------- 5.8/19.2 MB 151.6 kB/s eta 0:01:29
   ----------- ---------------------------- 5.8/19.2 MB 151.6 kB/s eta 0:01:29
   ----------- ---------------------------- 5.8/19.2 MB 151.6 kB/s eta 0:01:29
   ----------- ---------------------------- 5.8/19.2 MB 151.6 kB/s eta 0:01:29
   ------------ --------------------------- 6.0/19.2 MB 155.1 kB/s eta 0:01:26
   ------------ --------------------------- 6.0/19.2 MB 155.1 kB/s eta 0:01:26
   ------------ --------------------------- 6.0/19.2 MB 155.1 kB/s eta 0:01:26
   ------------ --------------------------- 6.0/19.2 MB 155.1 kB/s eta 0:01:26
   ------------ --------------------------- 6.0/19.2 MB 155.1 kB/s eta 0:01:26
   ------------- -------------------------- 6.3/19.2 MB 158.1 kB/s eta 0:01:22
   ------------- -------------------------- 6.3/19.2 MB 158.1 kB/s eta 0:01:22
   ------------- -------------------------- 6.3/19.2 MB 158.1 kB/s eta 0:01:22
   ------------- -------------------------- 6.3/19.2 MB 158.1 kB/s eta 0:01:22
   ------------- -------------------------- 6.3/19.2 MB 158.1 kB/s eta 0:01:22
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   ------------- -------------------------- 6.6/19.2 MB 167.3 kB/s eta 0:01:16
   -------------- ------------------------- 6.8/19.2 MB 167.3 kB/s eta 0:01:15
   -------------- ------------------------- 6.8/19.2 MB 167.3 kB/s eta 0:01:15
   -------------- ------------------------- 6.8/19.2 MB 167.3 kB/s eta 0:01:15
   -------------- ------------------------- 6.8/19.2 MB 167.3 kB/s eta 0:01:15
   -------------- ------------------------- 6.8/19.2 MB 167.3 kB/s eta 0:01:15
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   -------------- ------------------------- 7.1/19.2 MB 170.0 kB/s eta 0:01:12
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.3/19.2 MB 170.1 kB/s eta 0:01:10
   --------------- ------------------------ 7.6/19.2 MB 168.3 kB/s eta 0:01:10
   --------------- ------------------------ 7.6/19.2 MB 168.3 kB/s eta 0:01:10
   --------------- ------------------------ 7.6/19.2 MB 168.3 kB/s eta 0:01:10
   --------------- ------------------------ 7.6/19.2 MB 168.3 kB/s eta 0:01:10
   --------------- ------------------------ 7.6/19.2 MB 168.3 kB/s eta 0:01:10
   --------------- ------------------------ 7.6/19.2 MB 168.3 kB/s eta 0:01:10
   --------------- ------------------------ 7.6/19.2 MB 168.3 kB/s eta 0:01:10
   ---------------- ----------------------- 7.9/19.2 MB 167.2 kB/s eta 0:01:09
   ---------------- ----------------------- 7.9/19.2 MB 167.2 kB/s eta 0:01:09
   ---------------- ----------------------- 7.9/19.2 MB 167.2 kB/s eta 0:01:09
   ---------------- ----------------------- 7.9/19.2 MB 167.2 kB/s eta 0:01:09
   ---------------- ----------------------- 7.9/19.2 MB 167.2 kB/s eta 0:01:09
   ---------------- ----------------------- 7.9/19.2 MB 167.2 kB/s eta 0:01:09
   ---------------- ----------------------- 8.1/19.2 MB 170.6 kB/s eta 0:01:06
   ---------------- ----------------------- 8.1/19.2 MB 170.6 kB/s eta 0:01:06
   ---------------- ----------------------- 8.1/19.2 MB 170.6 kB/s eta 0:01:06

In [11]:
import fitz  # PyMuPDF

def extract_text_from_pdf(file_path):
    text = ""
    doc = fitz.open(file_path)
    
    for page in doc:
        text += page.get_text()
    
    return text

In [12]:
import os

folder_path = "resume"

resumes = []

for file in os.listdir(folder_path):
    if file.endswith(".pdf"):
        full_path = os.path.join(folder_path, file)
        text = extract_text_from_pdf(full_path)
        resumes.append(text)

In [13]:
resumes_clean = [clean_text(resume) for resume in resumes]
job_description_clean = clean_text(job_description)

In [14]:
all_texts = [job_description_clean] + resumes_clean

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(all_texts)

jd_vector = vectors[0]

scores = []

for i in range(1, vectors.shape[0]):
    score = cosine_similarity(jd_vector, vectors[i])[0][0]
    scores.append(score)

In [15]:
resume_files = []

for file in os.listdir(folder_path):
    if file.endswith(".pdf"):
        full_path = os.path.join(folder_path, file)
        text = extract_text_from_pdf(full_path)
        resumes.append(text)
        resume_files.append(file)

In [16]:
results = pd.DataFrame({
    "Resume": resume_files,
    "Score": scores
})

results["Score"] = (results["Score"] * 100).round(2)
results = results.sort_values(by="Score", ascending=False).reset_index(drop=True)

results

        Resume  Score
0  resume1.pdf  14.81
1  resume3.pdf  10.51
2  resume2.pdf   9.57

In [17]:
skills_list = [
    "python", "sql", "machine learning", "data analysis",
    "power bi", "excel", "tableau", "statistics",
    "deep learning", "nlp"
]

In [18]:
def extract_skills(text, skills_list):
    found_skills = []
    
    for skill in skills_list:
        if skill in text:
            found_skills.append(skill)
    
    return found_skills

In [19]:
jd_skills = extract_skills(job_description_clean, skills_list)
print("JD Skills:", jd_skills)

JD Skills: ['python', 'sql', 'machine learning', 'power bi']

In [20]:
resume_skills = []

for resume in resumes_clean:
    skills = extract_skills(resume, skills_list)
    resume_skills.append(skills)

In [21]:
matched_skills = []
missing_skills = []

for skills in resume_skills:
    matched = list(set(skills) & set(jd_skills))
    missing = list(set(jd_skills) - set(skills))
    
    matched_skills.append(matched)
    missing_skills.append(missing)

In [24]:
results["Matched Skills"] = matched_skills
results["Missing Skills"] = missing_skills

results

        Resume  Score Matched Skills                        Missing Skills
0  resume1.pdf  14.81          [sql]  [power bi, python, machine learning]
1  resume3.pdf  10.51  [python, sql]          [power bi, machine learning]
2  resume2.pdf   9.57  [python, sql]          [power bi, machine learning]

In [25]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\hp\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\hp\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\hp\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\hp\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\hp\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\hp\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.1.4)
Requirement already satisfied: attrs>=22.2.0 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)